### PR TITLE
Inject web3 only if Parity is connected.

### PR DESCRIPTION
**Pull request by tomusdrw**
Closes https://github.com/paritytech/parity/issues/5941

### CODE REVIEW

**Review by ngotchac — COMMENTED** [review]
Looks good, but just to be sure : if Parity is not running, it will try to get the node status every second, right ? Shouldn't it try for let's say 30 seconds, and then stop trying ? No need to use unnecessary resources IMO

**Comment by tomusdrw** [comment]
Fair point, it should only request something from background script, but makes sense to make it less frequent. I think it should try for a longer period of time than 30s, consider a scenario:
1. User enters a web3 site
2. Realizes that Parity is not running.
3. Runs the node. 

The web3 site should still start working after that and it may take more than 30s to actually do "2".

**Comment by ngotchac** [comment]
Yeah but wouldn't it be a OK if the user had to reload the page ? From a user POV, I'd rather reload a page if I find out my node is not running than having an extension running a function every second or so

**Comment by tomusdrw** [comment]
@ngotchac updated, could you have a look?

**Review by ngotchac — APPROVED** [review]

**Pull request merged**
